version: "3"
services:
  react-app:
    build: ./mern-docked-app
    restart: always
    container_name: react
    image: react
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
     - mern-dock
  
  # api-server:
  #   image: api-server
  #   container_name: node-api
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongo-db
  #   networks:
  #    - mern-dock

  # mongo-db:
  #  image: mongo:latest
  #  restart: always
  #  conatiner_name: mongo-db
  #  ports:
  #    - "27017:27017"
  #  networks:
  #    - mern-dock
  #  volumes:
  #   - ./mongo-data/:/data/db

networks:
  mern-dock:
    driver: bridge